// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    
    // --- SECTION 1: INTRO / META GUIDES ---
    // Since these are just 2 files in the root, we link them explicitly
    // to ensure they are always first.
    {
      type: 'doc',
      id: 'getting-started', 
      label: '🚀 Getting Started', // Optional: Add emoji if you like
    },
    {
      type: 'doc',
      id: 'markdown-cheatsheet',
      label: '✍️ Markdown Cheat Sheet',
    },

    // --- SEPARATOR ---
    {
      type: 'html',
      value: '<span style="border-top: 1px solid #dadde1; margin: 20px 0 10px 0; display: block;"></span><span style="color: #606770; font-size: 0.8em; font-weight: 700; letter-spacing: 0.1em; text-transform: uppercase;">Original SOP sections</span>',
      defaultStyle: true,
    },

    // --- SECTION 2: ORIGINAL SOPs ---
    // This grabs everything inside the "original_sops" folder
    {
      type: 'autogenerated',
      dirName: 'original_sops',
    },

    // --- SEPARATOR ---
    {
      type: 'html',
      value: '<span style="border-top: 1px solid #dadde1; margin: 20px 0 10px 0; display: block;"></span><span style="color: #606770; font-size: 0.8em; font-weight: 700; letter-spacing: 0.1em; text-transform: uppercase;">✨ Future Formats</span>',
      defaultStyle: true,
    },

    // --- SECTION 3: REVAMPED EXAMPLES ---
    // This grabs everything inside the "future_formats" folder
    {
      type: 'autogenerated',
      dirName: 'future_formats',
    },
  ],
};

export default sidebars;