// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By using 'autogenerated', Docusaurus will look at your 
  // /docs folder and build the menu automatically.
  // It saves you from manually updating this file ever again.
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generates sidebar from the docs folder structure
    },
    {
      type: 'html',
      value: '<span style="color: #606770; font-size: 0.8em; font-weight: 700; letter-spacing: 0.1em; text-transform: uppercase; margin-top: 20px; display: block; padding-left: 0.5rem;">✨ Examples of future format </span>',
      defaultStyle: true,
    },
  ],
};

export default sidebars;