// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    
    // --- SEPARATOR ---
    {
      type: 'html',
      value: '<div class="sidebar-section-header">ℹ️ Intro</div>', 
      defaultStyle: true,
    },
    // --- SECTION 1: INTRO / META GUIDES ---
    {
      type: 'doc',
      id: 'getting-started', 
      label: '🚀 Getting Started',
    },
    // {
    //   type: 'doc',
    //   id: 'markdown-cheatsheet',
    //   label: '✍️ Markdown Cheat Sheet',
    // },
    // --- SECTION 2: ORIGINAL SOP ---
    {
      type: 'html',
      value: '<div class="sidebar-section-header">📜 Original SOP</div>',
        defaultStyle: true,
    },
    {
      type: 'autogenerated',
      dirName: 'original_sop',
    },
    // --- SECTION 3: FUTURE FORMATS ---
    {
      type: 'html',
      value: '<div class="sidebar-section-header">✨ Future Formats</div>',
      defaultStyle: true,
    },
    {
      type: 'autogenerated',
      dirName: 'future_formats',
    },
  ],
};

export default sidebars;